name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Perft
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release -- --ignored
